# Generated by Django 5.2.7 on 2025-12-01 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='booking_source',
            field=models.CharField(choices=[('PATIENT', 'Patient'), ('DOCTOR', 'Doctor')], default='PATIENT', max_length=10),
        ),
    ]
