# Generated by Django 5.1.6 on 2026-01-04 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('appointments', '0005_remove_dailyslot_price_alter_appointment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file_url', models.URLField(max_length=500)),
                ('public_id', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document')], max_length=20)),
                ('temp_slot_id', models.IntegerField(blank=True, help_text='Used to link files during booking before appointment creation', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='appointments.appointment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='accounts.patient')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
